### PR TITLE
Add a font testing script

### PR DESCRIPTION
**Pull request by ghost**
I had to delete my old commit because it had too many problems with the script.

### CODE REVIEW

**Comment by xero** [comment]
this is the old alias i used for testing fonts

```
alias toiletlist='for i in ${TOILET_FONT_PATH:=/usr/share/figlet}/*.{t,f}lf; do j=${i##*/}; echo ""; echo "╓───── "$j; echo "╙────────────────────────────────────── ─ ─ "; echo ""; toilet -d "${i%/*}" -f "$j" "${j%.*}"; done'
```

but ive recently been using fzf like this
```
function toiletlist() {
	TXT=$1
	[ -z "$TXT" ] && TXT="{}"
	ls ${TOILET_FONT_PATH:=/usr/share/figlet} | sed 's/\.[^.]*$//' | fzf --preview="toilet -f {} ${TXT}" --preview-window=right:80%:noborder --color preview-bg:#1c1c1c
}
```

**Comment by 4G3NT** [comment]
Yeah, both of these solutions work. You could maybe include them in the README.md.

**Comment by 4G3NT** [comment]
I've placed the script in my own separate GitHub repository.

**Comment by 0xS0l0** [comment]
.

**Pull request closed without merging**
